# Generated by Django 4.2.2 on 2023-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_rename_name_composer_first_name_composer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='prereqs',
            field=models.ManyToManyField(null=True, to='pieces.piece'),
        ),
    ]
