# Generated by Django 4.2.2 on 2023-06-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_piece_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='techniques',
        ),
    ]
