# Generated by Django 4.2.2 on 2023-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0008_usertopieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofpiece',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
