# Generated by Django 4.2.2 on 2023-08-01 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0009_composer_description_period_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopieces',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
