# Generated by Django 4.2.2 on 2023-08-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0010_usertopieces_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopieces',
            name='date_updated',
        ),
    ]
