# Generated by Django 4.2.2 on 2023-08-01 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0011_remove_usertopieces_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopieces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 1, 10, 46, 38, 85876, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertopieces',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
