# Generated by Django 4.2.2 on 2023-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0012_usertopieces_created_at_usertopieces_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avg_difficulty',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
