# Generated by Django 4.2.2 on 2023-09-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0014_piece_sorting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='sorting_title',
        ),
    ]
