# Generated by Django 4.2.2 on 2023-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0015_remove_piece_sorting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='sorting_order',
            field=models.TextField(default='01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofpiece',
            name='sorting_order',
            field=models.TextField(default='01'),
            preserve_default=False,
        ),
    ]
