# Generated by Django 4.2.2 on 2023-06-29 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0007_piece_techniques'),
        ('core', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
