# Generated by Django 4.2.2 on 2023-06-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usertopieces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToPieces',
        ),
    ]
